#!/bin/bash
# shellcheck disable=SC2016 # dpkg-deb --showformat strings are literal
# Download the arm64 .deb packages listed in packages.txt, plus their full
# dependency closure, into vendor/debian-trixie-arm64/debs, and write
# SHA256SUMS and MANIFEST.txt next to them.
#
# The host's own apt state is not touched: apt runs with a private sources
# list, cache and an empty dpkg status, so it resolves the closure as if
# nothing were installed. Multiarch does not need to be enabled.
#
# Needs: apt-get, dpkg-deb, and the archive keyring for the mirror (on Debian
# that is the debian-archive-keyring package).
#
# Environment overrides (the defaults are Debian 13 "trixie"):
#   VENDOR    output directory          (vendor/debian-trixie-arm64)
#   SOURCES   apt sources, one per line ("deb <uri> <suite> <components>")
#   KEYRING   keyring that signs SOURCES (/usr/share/keyrings/debian-archive-keyring.gpg)
set -euo pipefail

REPO=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
VENDOR="${VENDOR:-$REPO/vendor/debian-trixie-arm64}"
KEYRING="${KEYRING:-/usr/share/keyrings/debian-archive-keyring.gpg}"
SOURCES="${SOURCES:-deb http://deb.debian.org/debian trixie main
deb http://deb.debian.org/debian trixie-updates main
deb http://security.debian.org/debian-security trixie-security main}"

test -f "$KEYRING" || { echo "missing keyring: $KEYRING" >&2; exit 1; }
strip_list() { sed -e 's/#.*//' -e 's/[[:space:]]//g' -e '/^$/d' "$1"; }
mapfile -t PACKAGES < <(strip_list "$VENDOR/packages.txt")
EXCLUDE=()
if [ -f "$VENDOR/exclude.txt" ]; then
  mapfile -t EXCLUDE < <(strip_list "$VENDOR/exclude.txt")
fi
test "${#PACKAGES[@]}" -gt 0 || { echo "no packages in $VENDOR/packages.txt" >&2; exit 1; }

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/lists/partial" "$WORK/archives/partial" "$WORK/sources.list.d" \
  "$WORK/preferences.d" "$WORK/apt.conf.d"
printf '%s\n' "$SOURCES" | sed "s#^deb #deb [arch=arm64 signed-by=$KEYRING] #" > "$WORK/sources.list"

APT=(apt-get
  -o "Dir::Etc::sourcelist=$WORK/sources.list"
  -o "Dir::Etc::sourceparts=$WORK/sources.list.d"
  -o "Dir::Etc::preferences=$WORK/preferences"
  -o "Dir::Etc::preferencesparts=$WORK/preferences.d"
  -o "Dir::Etc::parts=$WORK/apt.conf.d"
  -o "Dir::State::lists=$WORK/lists"
  -o "Dir::State::status=/dev/null"
  -o "Dir::State::extended_states=$WORK/extended_states"
  -o "Dir::Cache=$WORK"
  -o "Dir::Cache::archives=$WORK/archives"
  -o APT::Architecture=arm64
  -o APT::Architectures::=arm64
  -o APT::Install-Recommends=false
  -o APT::Install-Suggests=false
  -o APT::Sandbox::User=root
  -o Acquire::Languages=none
  -o Debug::NoLocking=true
)

"${APT[@]}" update
"${APT[@]}" install -y --download-only "${PACKAGES[@]}"

shopt -s nullglob
debs=("$WORK/archives"/*.deb)
test "${#debs[@]}" -gt 0 || { echo "apt downloaded nothing" >&2; exit 1; }

rm -rf "$VENDOR/debs"
mkdir -p "$VENDOR/debs"
for deb in "${debs[@]}"; do
  name=$(dpkg-deb --show --showformat='${Package}' "$deb")
  for pattern in "${EXCLUDE[@]}"; do
    # shellcheck disable=SC2053 # glob match is intended
    if [[ $name == $pattern ]]; then
      echo "excluded $name"
      continue 2
    fi
  done
  # Large files are rejected by GitHub above 100 MB.
  size=$(stat -c %s "$deb")
  if [ "$size" -ge 100000000 ]; then
    echo "too large for git: $(basename "$deb") ($size bytes)" >&2
    exit 1
  fi
  cp "$deb" "$VENDOR/debs/"
done

(
  cd "$VENDOR/debs"
  sha256sum -- *.deb > ../SHA256SUMS
)
{
  echo "# Generated by scripts/vendor-debs.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Sources:"
  printf '%s\n' "$SOURCES" | sed 's/^/#   /'
  for deb in "$VENDOR/debs"/*.deb; do
    dpkg-deb --show --showformat='${Package} ${Version} ${Architecture}\n' "$deb"
  done | awk '{ printf "%-48s %-40s %s\n", $1, $2, $3 }'
} > "$VENDOR/MANIFEST.txt"

count=$(find "$VENDOR/debs" -name '*.deb' | wc -l)
echo "vendored $count packages ($(du -sh "$VENDOR/debs" | cut -f1)) into $VENDOR"
